### ISSUE TITLE
Regarding performance issue w.r.t to pyboolector library

### ISSUE THREAD

**Issue by aneels3** [fvutils/pyvsc#59]
Hi @mballance 

I have done the profiling in our generator to find out the bottleneck of the poor performance.
After going through the profiling data it seems like `Sat` method pyboolector is taking almost 80% of the total internal execution time. 
I am attaching the profiling data here for your reference which is for 100 instructions only.
![image](https://user-images.githubusercontent.com/32580268/113056562-9178d000-91c9-11eb-9c1f-90b2e2fbbd85.png)
I am curious to know what exactly `Sat` method of pyboolector does while randomizing the data using `vsc` module and how can I minimize this as our generator is growing with time and the same is reflected in the performance.
I am not sure if I should be raising this issue here but I would be highly obliged if you can provide me a way to maximize the performance.

**Comment by aneels3** [comment]
Adding @hodjat91 for visibility.

**Comment by mballance** [comment]
Hi @aneels3,
    The `Sat` method performs solving of the constraint equations. It's used for two purposes -- one to establish correct (but non-random) values for fields and one to provoke random values on the variables such that they still satisfy the constraints. 
Do you know how many calls to the `randomize` API the generator makes in order to generate 100 instructions? I see that there are ~800 calls to `Sat`. Knowing how many total calls to randomize you make would give a clue on how many solves are done (on average) to produce each solution to a `randomize` call.
One thing to look out for are constraints on arrays. Since arrays are unrolled, a fairly simple-looking constraint can turn into something quite large and difficult for the solver to process.

Best Regards,
Matthew

**Comment by edcote** [comment]
I found setting EN_DEBUG = 1 in randomizer.py to identify to large constraints.

Do you know why, specifically, the solver would have a problem with simple constraints on arrays, e.g., each element of an array is between a range:

```
Pre-Randomize: RandSet
  Field: grid.<unknown>[98] [[256, 2047]]
  Constraint: (grid.<unknown>[98] <= 2047);
  Constraint: (grid.<unknown>[98] >= 256);
```

Are you aware of a hook in pyboolector to profile solve time?

**Comment by aneels3** [comment]
Hi @mballance 
Sorry for the delay on this.
As per our last discussion, I have created two branches in our forked repository [profiling_with_constraints](https://github.com/saurabhsingh-pvips/riscv-dv/tree/profiling_with_constraints) and [prof_without_constraints](https://github.com/saurabhsingh-pvips/riscv-dv/tree/prof_without_constraints).

**The command to run the test:**
`python3 run.py --test=riscv_arithmetic_basic_test --iteration 1 --simulator pyflow --gen_timeout 3000`

The **riscv_arithmetic_basic_test** will run without the [directed case](https://github.com/saurabhsingh-pvips/riscv-dv/blob/9739b34318c5dde9c4872ea38163d922bacbc0ba/yaml/base_testlist.yaml#L40) for now and with 1000 instr_cnt.
You can decrease or increase the instr_cnt from [here](https://github.com/saurabhsingh-pvips/riscv-dv/blob/9739b34318c5dde9c4872ea38163d922bacbc0ba/pygen/pygen_src/riscv_instr_gen_config.py#L39)

I have also included the [logs](https://github.com/saurabhsingh-pvips/riscv-dv/tree/prof_without_constraints/prof_logs) that I have generated for **with_constraints** and **without_constraints** for your reference.

Surprisingly, I see some difference in time for the generation which is about ~100 sec but there is not much effect on the number of ncalls for the **Sat** method.


**Note:** 
With the latest PyVSC release this https://github.com/fvutils/pyvsc/issues/43 issue is creating problems while running the test but this time with a different error. I am investigating it and will address this in a separate issue or reopen #43.
For now, you need to downgrade the PyVSC version to a particular release(0.3.7.20210523.1) to make it work.

Regards,
Anil

**Comment by mballance** [comment]
Hi @aneels3,
    Thank you for the instructions. I'll begin investigating when I have a chance (likely at the weekend). 

Best Regards,
Matthew

**Comment by aneels3** [comment]
Thanks @mballance 
Looking forward to hearing from you.

Best, 
Anil

**Comment by mballance** [comment]
Hi @aneels3,
    My first step in investigating this is to establish some baseline numbers: performance for pyflow and performance for a simulator. I am using PyVSC 0.4.6. Using Questa as the simulator, I see the following when running the command above:
- pyflow: 23.55s
- questa: 11.57s

If I understand the note above, you see ~100s to run the command using pyflow. Am I reading this correctly? Please confirm how long the pyflow and simulator runs take in your environment. If possible, please use Questa so we can do an exact comparison. 

Can you confirm the version of PyBoolector that you are using (pip show pyboolector)? I have 3.2.2.20210617.2  installed in my environment.

Thanks and Best Regards,
Matthew

**Comment by mballance** [comment]
Hi @aneels3,
    Okay, I've added in a very rudimentary profiler to collect statistics on what classes are being randomized and their characteristics. It is enabled by setting the VSC_PROFILE environment variable to '1', and produces information like the following at the end of execution:
```
PyVSC Profile:
RandSites:
    "riscv_instr_gen_config @ /project/fun/pyvsc/perf_investigation/riscv-dv-with_constraints/pygen/pygen_src/test/riscv_instr_base_test.py:73":
      count: 1
      randinfo:
        sets: 5
        cfields: 25
      time: 26
        min: 26
        max: 26
        avg: 26
      sat-calls: 22
        min: 22
        max: 22
        avg: 22
    "<unknown> @ pygen/pygen_src/riscv_asm_program_gen.py:393":
      count: 30
      randinfo:
        sets: 1
        cfields: 1
      time: 44
        min: 1
        max: 2
        avg: 1
      sat-calls: 120
        min: 4
        max: 4
        avg: 4
    "riscv_privileged_common_seq @ pygen/pygen_src/riscv_asm_program_gen.py:519":
      count: 1
      randinfo:
        sets: 0
        cfields: 0
      time: 0
        min: 0
        max: 0
        avg: 0
      sat-calls: 0
        min: 0
        max: 0
        avg: 0
    "riscv_instr @ pygen/pygen_src/riscv_instr_stream.py:260":
      count: 1000
      randinfo:
        sets: 3
        cfields: 15
      time: 9543
        min: 6
        max: 99
        avg: 9
      sat-calls: 7611
        min: 5
        max: 10
        avg: 7
```
We can see that most of the total time is going into randomization of the 'riscv_instr' class. One opportunity for performance improvement here would be to somehow reduce the number of SAT calls. 

By the way, I noticed that the repo you pointed me to had profiling enabled. I disabled profiling to see what overhead it might be introducing. My runtime with profiling disabled is 15.379s.

Can you confirm your total runtime with profiling disabled?
